language: python
python:
  - "3.8"
# command to install dependencies
install:
  - conda install -c conda-forge wxpython
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest